### ISSUE TITLE
After having installed the plug-in the wiki was not responding anymore.

### ISSUE THREAD

**Issue by bgenere** [cosmocode/dokuwiki-plugin-sentry#10]
I have currently an issue with the Config Manager plugin that send me a blank screen.
I have activated allowdebug but did not get any message.

So I installed this module through the module manager to get something.
Obvously I was not able to configure this module through the config manager so I changed the default.php configuration file of the module with the following content :

$conf['dsn']    = 'https://be319b0be0ab459aaaaf1592a081b2ad@sentry.io/1455382';
$conf['env']    = 'wikicafe';
$conf['errors'] = 32767 ;

When I refreshed the start page of the wiki I get a blank screen, and absolutely no message in my sentry account.

I have unabled this module manually adding the line 
$plugins['sentry'] = 0; 
in the proper file and my wiki is now back (except the config manager of course).

Any idea why I get this issue ?

Thanks

**Comment by splitbrain** [comment]
Well, when the config manager isn't working you have some deeper rooted problems. Check your logs. My guess is that your PHP version is too old.

**Comment by bgenere** [comment]
For your information, my PHP is 7.2.
I just go to my server log and get this funny message on all requests : 

[Thu May 09 12:11:05.176901 2019] [access_compat:error] [pid 14864:tid 47449443997440] [client 176.137.26.90:0] AH01797: client denied by server configuration: /home/cafeanais/wikicafe.reseauanais.fr/data/dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png, referer: https://test.reseauanais.fr/

This is the only message I get there, should I panic however ? ;-).
I am actually finding some issues with core modules so I will report them on DoKuWiki repo.

Thanks for your answers
